---
# Install and configure nginx

- name: Install nginx
  yum: name=nginx state=latest
  notify: restart nginx
  tags: nginx

- name: Copy nginx configuration file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx
  tags: nginx

- name: Open port 80 for nginx
  command: /sbin/iptables -A INPUT -p tcp --dport 80 -j ACCEPT
  tags: nginx

- name: Save iptables rules
  command: /sbin/service iptables save
  tags: nginx

- name: Start nginx
  service: name=nginx state=started enabled=yes
  tags: nginx
