---
# Create a deployment user and group

- name: Create deployment group
  group: name=rletters_deploy
  tags: user

- name: Create deployment user
  user: name=rletters_deploy group=rletters_deploy home=/opt/rletters password={{ deploy_pass | password_hash('sha512') }}
  tags: user
