---
# Deploy a complete RLetters stack (including web, DB, and Solr)

- name: apply common configuration to all nodes
  hosts: all
  sudo: yes

  roles:
    - common

- name: confgure and deploy the database server
  hosts: dbserver
  sudo: yes

  roles:
    - db

- name: configure and deploy the Solr server
  hosts: solrserver
  sudo: yes

  roles:
    - solr

- name: confgure and deploy the web servers
  hosts: webservers
  sudo: yes

  roles:
    - web
