---
# Install Java 1.8.  It's needed for both Tomcat/Solr and the web hosts, so
# just get it working everywhere.

- name: Install Java 1.8 (RHEL/CentOS)
  package: name={{ item }} state=present
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
  when: is_rpm
  tags: java

- name: Install Java 1.8 (Arch)
  package: name={{ item }} state=present
  with_items:
    - jre8-openjdk
    - jdk8-openjdk
  when: is_arch
  tags: java

- name: Install profile snippet to set JAVA_HOME
  template: src=java.sh.j2 dest=/etc/profile.d/java.sh
  tags: java

- name: Permit JAVA_HOME for root in sudo environment
  lineinfile: dest=/etc/sudoers state=present regexp="^Defaults\s+env_keep.+JAVA_HOME" line="Defaults env_keep += \"JAVA_HOME\""
  tags: java

- name: Permit LD_LIBRARY_PATH for root in sudo environment
  lineinfile: dest=/etc/sudoers state=present regexp="^Defaults\s+env_keep.+LD_LIBRARY_PATH" line="Defaults env_keep += \"LD_LIBRARY_PATH\""
  tags: java
