---
# Configure the EPEL repo
- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo
  tags: yum

- name: Copy the EPEL GPG key
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg
  tags: yum

- name: Install SELinux Python bindings for Ansible
  yum: name=libselinux-python state=present
  tags: yum

- name: Copy the PostgreSQL repository definition
  copy: src=pgdg-93-redhat.repo dest=/etc/yum.repos.d/pgdg-93-redhat.repo
  tags: yum

- name: Copy the PostgreSQL GPG key
  copy: src=RPM-GPG-KEY-PGDG-93 dest=/etc/pki/rpm-gpg
  tags: yum

- name: Copy the Nginx repository definition (CentOS)
  copy: src=nginx-centos.repo dest=/etc/yum.repos.d/nginx.repo
  when: ansible_distribution == 'CentOS'
  tags: yum

- name: Copy the Nginx repository definition (RHEL)
  copy: src=nginx-rhel.repo dest=/etc/yum.repos.d/nginx.repo
  when: ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
  tags: yum

- name: Enable the yum cache
  lineinfile: dest=/etc/yum.conf regexp="^keepcache=" line="keepcache=1" state=present
  tags: yum
