---
# Configure basic repos and packages
- name: Install some basic system utilities
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - wget
  tags: yum

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo
  tags: yum

- name: Copy the EPEL GPG key
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg
  tags: yum

- name: Copy the PostgreSQL repository definition (CentOS)
  copy: src=pgdg-94-centos.repo dest=/etc/yum.repos.d/pgdg-94-centos.repo
  when: ansible_distribution == 'CentOS'
  tags: yum

- name: Copy the PostgreSQL repository definition (RHEL)
  copy: src=pgdg-94-redhat.repo dest=/etc/yum.repos.d/pgdg-94-redhat.repo
  when: ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
  tags: yum

- name: Copy the PostgreSQL GPG key
  copy: src=RPM-GPG-KEY-PGDG-94 dest=/etc/pki/rpm-gpg
  tags: yum

- name: Copy the Nginx repository definition (CentOS)
  copy: src=nginx-centos.repo dest=/etc/yum.repos.d/nginx.repo
  when: ansible_distribution == 'CentOS'
  tags: yum

- name: Copy the Nginx repository definition (RHEL)
  copy: src=nginx-rhel.repo dest=/etc/yum.repos.d/nginx.repo
  when: ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
  tags: yum

- name: Enable the yum cache
  lineinfile: dest=/etc/yum.conf regexp="^keepcache=" line="keepcache=1" state=present
  tags: yum
