---
# Install and configure nginx

- name: Install nginx
  yum: name=nginx state=present
  tags: nginx

- name: Copy nginx configuration file
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  tags: nginx
